name: Update flake.lock
on:
  schedule:
    - cron: "0 12 * * 1" # Mondays 12:00 UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: DeterminateSystems/nix-installer-action@b67ad2f0e8376a0bc947db191e4484285b6f5b56 # main @ 2026-09-02
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.FLAKE_UPDATE_TOKEN }}
      - uses: DeterminateSystems/update-flake-lock@01467157fe94fd33c160f7311a78689ceaad3ec4 # main @ 2026-09-02
        with:
          token: ${{ secrets.FLAKE_UPDATE_TOKEN }}
          pr-title: "flake: update inputs"
          pr-labels: dependencies
